import type { Asset, ForumCategory, ForumThread, Notification, Stats } from "./types"

export const mockAssets: Asset[] = [
  {
    id: "1",
    title: "Prism - Banking",
    description: "Advanced banking system with ATM, bank robbery, and more.",
    category: "scripts",
    framework: "standalone",
    version: "1.0.0",
    price: "free",
    image: "/banking-system-ui-dark-theme.jpg",
    downloads: 1250,
    rating: 4.8,
    author: "PrismDev",
    createdAt: "2024-01-15",
    tags: ["banking", "economy", "atm"],
  },
  {
    id: "2",
    title: "Decrypt V7 No",
    description: "Vehicle unlock and hotwire system with animations.",
    category: "scripts",
    framework: "standalone",
    version: "1.0.0",
    price: "free",
    image: "/car-unlock-system-gta.jpg",
    downloads: 890,
    rating: 4.5,
    author: "DecryptTeam",
    createdAt: "2024-01-20",
    tags: ["vehicle", "unlock", "hotwire"],
  },
  {
    id: "3",
    title: "Prism - Appearance",
    description: "Complete character customization with clothing stores.",
    category: "scripts",
    framework: "standalone",
    version: "1.0.0",
    price: "free",
    image: "/character-customization-ui.jpg",
    downloads: 2100,
    rating: 4.9,
    author: "PrismDev",
    createdAt: "2024-02-01",
    tags: ["appearance", "clothing", "customization"],
  },
  {
    id: "4",
    title: "Electron AC",
    description: "Advanced anti-cheat system for FiveM servers.",
    category: "scripts",
    framework: "standalone",
    version: "1.0.0",
    price: "free",
    image: "/anticheat-security-shield.jpg",
    downloads: 3500,
    rating: 4.7,
    author: "ElectronTeam",
    createdAt: "2024-02-10",
    tags: ["anticheat", "security", "protection"],
  },
  {
    id: "5",
    title: "Legion Square MLO",
    description: "High-quality Legion Square interior with multiple floors.",
    category: "mlo",
    framework: "standalone",
    version: "2.0.0",
    price: "premium",
    image: "/gta-legion-square-building-interior.jpg",
    downloads: 450,
    rating: 4.9,
    author: "MLOStudio",
    createdAt: "2024-02-15",
    tags: ["interior", "legion", "building"],
  },
  {
    id: "6",
    title: "Lamborghini Pack",
    description: "10 high-quality Lamborghini vehicles with custom handling.",
    category: "vehicles",
    framework: "standalone",
    version: "1.5.0",
    price: "premium",
    image: "/lamborghini-sports-car-gta.jpg",
    downloads: 780,
    rating: 4.8,
    author: "AutoMods",
    createdAt: "2024-02-20",
    tags: ["lamborghini", "supercar", "vehicle"],
  },
  {
    id: "7",
    title: "Police EUP Pack",
    description: "Complete police uniform pack with multiple departments.",
    category: "clothing",
    framework: "standalone",
    version: "3.0.0",
    price: "free",
    image: "/police-uniform-gta-roleplay.jpg",
    downloads: 1890,
    rating: 4.6,
    author: "EUPMaster",
    createdAt: "2024-03-01",
    tags: ["police", "uniform", "eup"],
  },
  {
    id: "8",
    title: "Hospital MLO",
    description: "Fully detailed hospital interior with operating rooms.",
    category: "mlo",
    framework: "standalone",
    version: "1.0.0",
    price: "premium",
    image: "/hospital-interior-gta-mlo.jpg",
    downloads: 620,
    rating: 4.9,
    author: "MLOStudio",
    createdAt: "2024-03-05",
    tags: ["hospital", "medical", "interior"],
  },
  {
    id: "9",
    title: "Advanced Garage",
    description: "Multi-level garage system with impound and tuning.",
    category: "scripts",
    framework: "esx",
    version: "2.1.0",
    price: "free",
    image: "/garage-system-gta.jpg",
    downloads: 1560,
    rating: 4.7,
    author: "GarageScripts",
    createdAt: "2024-02-25",
    tags: ["garage", "vehicles", "tuning"],
  },
  {
    id: "10",
    title: "Drug System",
    description: "Complete drug production and selling system.",
    category: "scripts",
    framework: "qbcore",
    version: "1.3.0",
    price: "premium",
    image: "/drug-system-dark-ui.jpg",
    downloads: 890,
    rating: 4.4,
    author: "QBScripts",
    createdAt: "2024-03-10",
    tags: ["drugs", "economy", "illegal"],
  },
  {
    id: "11",
    title: "BMW M5 F90",
    description: "High-quality BMW M5 with custom tuning parts.",
    category: "vehicles",
    framework: "standalone",
    version: "1.0.0",
    price: "free",
    image: "/bmw-m5-f90-gta-style.jpg",
    downloads: 2340,
    rating: 4.9,
    author: "AutoMods",
    createdAt: "2024-03-15",
    tags: ["bmw", "sedan", "german"],
  },
  {
    id: "12",
    title: "Fire Station MLO",
    description: "Complete fire station interior with truck bays.",
    category: "mlo",
    framework: "standalone",
    version: "1.2.0",
    price: "free",
    image: "/fire-station-interior-gta.jpg",
    downloads: 780,
    rating: 4.6,
    author: "MLOStudio",
    createdAt: "2024-03-20",
    tags: ["fire", "emergency", "building"],
  },
]

export const mockForumCategories: ForumCategory[] = [
  {
    id: "1",
    name: "Announcements",
    description: "Official announcements and updates",
    icon: "megaphone",
    threadCount: 15,
    color: "#a855f7",
  },
  {
    id: "2",
    name: "General Discussion",
    description: "General chat and community discussions",
    icon: "message-circle",
    threadCount: 234,
    color: "#22c55e",
  },
  {
    id: "3",
    name: "Help & Support",
    description: "Get help with scripts and resources",
    icon: "help-circle",
    threadCount: 89,
    color: "#f59e0b",
  },
  {
    id: "4",
    name: "Script Requests",
    description: "Request new scripts and features",
    icon: "code",
    threadCount: 156,
    color: "#3b82f6",
  },
  {
    id: "5",
    name: "Showcase",
    description: "Show off your servers and creations",
    icon: "star",
    threadCount: 78,
    color: "#e879f9",
  },
]

export const mockThreads: ForumThread[] = [
  {
    id: "1",
    title: "Welcome to FiveM Tools V7!",
    content:
      "Welcome to the official community forum. Here you can discuss scripts, get help, share your creations, and connect with other server owners. Please read the rules before posting.",
    category: "Announcements",
    author: {
      id: "admin",
      username: "FiveM Admin",
      email: "admin@fivemtools.net",
      avatar: "/admin-avatar-purple.jpg",
      discordId: "123456789",
      membership: "admin",
      downloads: 0,
      reputation: 1000,
      points: 5000,
      achievements: [],
      createdAt: "2024-01-01",
    },
    replies: 45,
    likes: 120,
    views: 2500,
    isPinned: true,
    isLocked: false,
    createdAt: "2024-01-01",
  },
  {
    id: "2",
    title: "How to install ESX scripts properly?",
    content:
      "I need help installing ESX scripts. I keep getting errors when I try to start the resource. Can someone explain the proper installation steps?",
    category: "Help & Support",
    author: {
      id: "user1",
      username: "NewServer",
      email: "user@example.com",
      avatar: "/gamer-avatar.png",
      discordId: "987654321",
      membership: "free",
      downloads: 5,
      reputation: 10,
      points: 50,
      achievements: [],
      createdAt: "2024-02-15",
    },
    replies: 12,
    likes: 8,
    views: 450,
    isPinned: false,
    isLocked: false,
    createdAt: "2024-03-01",
  },
  {
    id: "3",
    title: "[REQUEST] Advanced Police MDT System",
    content:
      "Looking for a comprehensive MDT system with vehicle registration, warrant management, and report filing. Preferably QBCore compatible.",
    category: "Script Requests",
    author: {
      id: "user2",
      username: "RPServer_Owner",
      email: "owner@rpserver.com",
      avatar: "/gamer-avatar-blue.jpg",
      discordId: "456789123",
      membership: "vip",
      downloads: 50,
      reputation: 85,
      points: 420,
      achievements: [],
      createdAt: "2024-01-20",
    },
    replies: 28,
    likes: 45,
    views: 890,
    isPinned: false,
    isLocked: false,
    createdAt: "2024-03-05",
  },
  {
    id: "4",
    title: "Showcase: My Custom Police Department Interior",
    content:
      "Check out my latest MLO creation - a fully detailed police department with cells, interrogation rooms, and a underground parking garage.",
    category: "Showcase",
    author: {
      id: "user3",
      username: "MLOCreator",
      email: "creator@mlo.com",
      avatar: "/studio-avatar.jpg",
      discordId: "789456123",
      membership: "vip",
      downloads: 120,
      reputation: 250,
      points: 1200,
      achievements: [],
      createdAt: "2024-01-05",
    },
    replies: 67,
    likes: 189,
    views: 2100,
    isPinned: false,
    isLocked: false,
    createdAt: "2024-03-08",
  },
  {
    id: "5",
    title: "New Feature: Real-time Forum Updates",
    content:
      "We have implemented real-time updates for the forum. You will now see new posts and replies instantly without refreshing the page!",
    category: "Announcements",
    author: {
      id: "admin",
      username: "FiveM Admin",
      email: "admin@fivemtools.net",
      avatar: "/admin-avatar-purple.jpg",
      discordId: "123456789",
      membership: "admin",
      downloads: 0,
      reputation: 1000,
      points: 5000,
      achievements: [],
      createdAt: "2024-01-01",
    },
    replies: 23,
    likes: 78,
    views: 1200,
    isPinned: true,
    isLocked: false,
    createdAt: "2024-03-10",
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "1",
    type: "reply",
    title: "New Reply",
    message: "Someone replied to your thread",
    read: false,
    createdAt: "2024-03-10T10:00:00Z",
  },
  {
    id: "2",
    type: "like",
    title: "New Like",
    message: "Your post received a like",
    read: false,
    createdAt: "2024-03-10T09:30:00Z",
  },
  {
    id: "3",
    type: "system",
    title: "Welcome!",
    message: "Welcome to FiveM Tools V7",
    read: true,
    createdAt: "2024-03-09T12:00:00Z",
  },
]

export const mockStats: Stats = {
  onlineUsers: 3,
  totalMembers: 30,
  totalAssets: 1500,
  totalDownloads: 25000,
}
